### ISSUE TITLE
HttpClientHalder 动态证书怎么处理

### ISSUE THREAD

**Issue by anhuisunfei** [Senparc/Senparc.CO2NET#100]
``` csharp
   HttpClientHandler handler = HttpClientHelper.GetHttpClientHandler(cookieContainer, SenparcHttpClientWebProxy, DecompressionMethods.GZip);

            if (checkValidationResult)
            {
                handler.ServerCertificateCustomValidationCallback = new Func<HttpRequestMessage, X509Certificate2, X509Chain, SslPolicyErrors, bool>(CheckValidationResult);
            }

            if (cer != null)
            {
                handler.ClientCertificates.Add(cer);
            }
  var senparcHttpClient = SenparcDI.GetRequiredService<SenparcHttpClient>();
 senparcHttpClient.SetCookie(new Uri(url), cookieContainer);//设置Cookie
```

HttpClientHalder 动态证书怎么处理,这里的handler对象没看到使用

**Comment by JeffreySu** [comment]
@anhuisunfei  新的preview版本中已经有提供解决方案，只需要按照微信SDK的Sample下的appsettings.json设置微信支付的新参数即可（不需要手写任何代码）。

这个功能正在测试中，还发现有无法使用的情况，欢迎一起加入测试。

**Comment by anhuisunfei** [comment]
@JeffreySu 这种方法还是无法避免由于证书更新、证书新增需要应用重启的问题。

**Comment by JeffreySu** [comment]
@anhuisunfei  不需要，如果更新，你直接重新注册就行了，我们已经把全局 ServiceCollection 缓存到 SenparcDI 下面，你可以通过  Senparc.CO2NET.SenparcDI.GetIServiceProvider() 获取到这个对象，重新注册，设置完成之后，使用 SenparcDI.ResetGlobalIServiceProvider() 生成新的 Provider，立即生效。

**Comment by anhuisunfei** [comment]
@JeffreySu 了解 、涉及到的项目比较多 我在评估下要不要用这种方式 感谢苏总！

**Comment by KINGGUOKUN** [comment]
core 3.1 HttpClient默认是启用服务端证书校验的，而CO2NET默认没有关闭或者默认直接通过服务端证书校验，导致请求微信相关API时候出错：The SSL connection could not be established, see inner exception。目前我的临时解决方案如下：
services.AddHttpClient<SenparcHttpClient>("elite-wechat")
                         .ConfigurePrimaryHttpMessageHandler(() =>
                         {
                             var httpClientHandler = HttpClientHelper.GetHttpClientHandler(null, RequestUtility.SenparcHttpClientWebProxy, System.Net.DecompressionMethods.GZip);
                             //httpClientHandler.ClientCertificates.Add(cert);
                             httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errir) => true;

                             return httpClientHandler;
                         });
