### ISSUE TITLE
Core 控制台应用程序中对RegisterService.Start的使用

### ISSUE THREAD

**Issue by Hsinky** [Senparc/Senparc.CO2NET#11]
在core 2.0版本中引入0.1.6的Senparc.CO2NET，注册微信公众号服务时，调用RegisterService Start()需要参数IHostingEnvironment和SenparcSetting，不知如何传环境参数
![image](https://user-images.githubusercontent.com/10111222/42299979-aad091de-8040-11e8-8962-1cb17107b97e.png)

**Comment by JeffreySu** [comment]
已经发布一个新版本：https://www.nuget.org/packages/Senparc.CO2NET/0.1.8
注意新版本的第二个bool类型可以不用输入了。

**Comment by JeffreySu** [comment]
有更新了一个版本：https://www.nuget.org/packages/Senparc.Co2NET
单元测试中也可以跑了，如果还有问题欢迎ReOpen继续讨论，谢谢！

**Comment by qinzhenlong** [comment]
![image](https://user-images.githubusercontent.com/18487533/42937948-352bfa56-8b83-11e8-82f3-377ac0355604.png)
这个地方报错了 不知道什么原因 配置都有
![image](https://user-images.githubusercontent.com/18487533/42937975-575b32ea-8b83-11e8-8155-877e0bdc57bc.png)

安装版本
![image](https://user-images.githubusercontent.com/18487533/42937999-6d08e3c6-8b83-11e8-8644-aa79b8962396.png)

**Comment by qinzhenlong** [comment]
这个地方报错不知道什么原因啊
![image](https://user-images.githubusercontent.com/18487533/42938055-9bd1727c-8b83-11e8-9d07-4063fb48aec5.png)

配置：
![image](https://user-images.githubusercontent.com/18487533/42938077-ac03cf00-8b83-11e8-95e6-3deb15bc92d2.png)

安装版本：
![image](https://user-images.githubusercontent.com/18487533/42938100-b7364d9e-8b83-11e8-846d-4e9b8c23903e.png)

**Comment by JeffreySu** [comment]
@qinzhenlong 看一下我们最新的demo，是不是启动注册的过程少了一些配置？
