### ISSUE TITLE
.Net Core项目调用上传临时素材接口时，若文件名称为中文，上传后的临时素材文件名被编码。

### ISSUE THREAD

**Issue by fairangel** [Senparc/Senparc.CO2NET#117]
**问题**：.Net Core项目调用上传临时素材接口(MediaApi.Upload())时，若文件名称为中文，上传后的临时素材文件名被编码。
**文件**：Senparc.CO2NET/Utilities/HttpUtility/RequestUtility.Common.cs
**行数**：246
**问题代码**：fileName = fileName.UrlEncode();

HttpUtility.HttpPost_Common_NetCore 方法中调用了CreateFileContent方法，该方法对获取到的文件名进行了UrlEncode。导致上传后的临时素材文件名被编码，使用该素材media_id发送文件时，文件名称无法正常显示中文，显示为被编码后的文本。

对应的HttpPost_Common_Net45方法则未进行编码，上传后的临时素材名称正常显示。

**Comment by JeffreySu** [comment]
已处理，谢谢！

**Comment by fairangel** [comment]
感谢处理！
目前仍存在编码问题，取消UrlEncode后，上传文件的名称被编码为MIME + Base64。
例：1.rar  =>  =_utf-8_B_5LiALnJhcg==_=

**Comment by JeffreySu** [comment]
你目前有具体的解决方案吗？
