### ISSUE TITLE
关于Senparc.CO2NET.RegisterServices.RegisterServices注册的问题

### ISSUE THREAD

**Issue by builderman** [Senparc/Senparc.CO2NET#122]
是不是应该可以在Startup.ConfigureService中配置:
services.AddSingleton<IRegisterService, RegisterService>();

然后在Configure中注入来的好看一些:
public void Configure(IApplicationBuilder app, IHostingEnvironment env, IRegisterService registerService)

这样更符合.net core的风格一点

**Comment by JeffreySu** [comment]
是的，理论上还可以简化，现在这个写法一定程度上是为了兼容 .net framework，后面我会考虑一下。
