### ISSUE TITLE
是否可以增加内置审批流程中添加附件功能？

### ISSUE THREAD

**Issue by caozhq** [Senparc/Senparc.CO2NET#161]
请参考更新后的 api

https://work.weixin.qq.com/api/doc/90000/90135/91853

参数 | 说明
-- | --
files | 附件列表
└ file_id | 文件id，该id为临时素材上传接口返回的的media_id，注：提单后将作为单据内容转换为长期文件存储；目前一个审批申请单，全局仅支持上传6个附件，否则将失败。

**Comment by JeffreySu** [comment]
收到！这个应该是在 https://github.com/JeffreySu/WeiXinMPSDK 下面的吧？

**Comment by JeffreySu** [comment]
@caozhq 之前已经在 Senparc.Weixin.Work.AdvancedAPIs.OA.OaApi.ApplyEvent() 方法中支持，非常感谢！

**Comment by JeffreySu** [comment]
Senparc.Weixin.Work.AdvancedAPIs.OA.OaApi.ApplyEvent() 方法中的 ApplyEventRequest 参数，里面的 apply_data.contents 是一个 string 对象，可以用于存放所有类型的请求，直接把 json 序列化就行。
