### ISSUE TITLE
nuget更新到最新版后，执行 app.UseSenparcGlobal 时的错误

### ISSUE THREAD

**Issue by thinkif** [Senparc/Senparc.CO2NET#181]
把 nuget更新到最新版后，执行 app.UseSenparcGlobal 时，出现报错 所在位置是 Senparc.CO2NET.Helpers.ReflectionHelper.GetStaticMember ， 错误为 System.NullReferenceException:“Object reference not set to an instance of an object.”

经过各种测试排查，发现使用 redis 时，如果只引用  Senparc.CO2NET.Cache.Redis 或 只引用 Senparc.CO2NET.Cache.CsRedis （相关配置均是对应的正确写法）就会出错，但是如果将两者都引用，但是只执行某一个配置，则不会出错

怀疑是在 app.UseSenparcGlobal 中尝试去找这2个

**Comment by thinkif** [comment]
搜了一下，可能跟 https://github.com/JeffreySu/WeiXinMPSDK/issues/2209 是同样的问题

**Comment by JeffreySu** [comment]
@thinkif  JeffreySu/WeiXinMPSDK#2209 对应问题已经有了更新，请查看。感谢您的关注，欢迎多提意见 😄
