### ISSUE TITLE
如何修改redis的前缀名？

### ISSUE THREAD

**Issue by Hareis** [Senparc/Senparc.CO2NET#184]
![image](https://user-images.githubusercontent.com/11290701/95947143-8fd86d00-0e20-11eb-9a50-b655b1f1f986.png)

请问下如何修改这个名字啊？

**Comment by JeffreySu** [comment]
参考这里：

https://github.com/JeffreySu/WeiXinMPSDK/blob/52a058ff123809c5455bd19b140310a5cf87e91d/Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/Startup.cs#L120

**Comment by Hareis** [comment]
> 参考这里：
> 
> https://github.com/JeffreySu/WeiXinMPSDK/blob/52a058ff123809c5455bd19b140310a5cf87e91d/Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/Startup.cs#L120

你可能没太理解我的意思。我想把 Senparc.Weixin.MP 的前缀名 改成 我司或者servicName

**Comment by Hareis** [comment]
> 参考这里：
> 
> https://github.com/JeffreySu/WeiXinMPSDK/blob/52a058ff123809c5455bd19b140310a5cf87e91d/Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/Startup.cs#L120

复制了一个完整的键名下来 感觉好长
`` Senparc:DefaultCO2NETCache111:Container:Senparc.Weixin.MP.Containers.AccessTokenBag:wx11676b7958ea1f6e``

**Comment by JeffreySu** [comment]
> > 参考这里：
> > https://github.com/JeffreySu/WeiXinMPSDK/blob/52a058ff123809c5455bd19b140310a5cf87e91d/Samples/netcore3.0-mvc/Senparc.Weixin.Sample.NetCore3/Startup.cs#L120
> 
> 复制了一个完整的键名下来 感觉好长
> ` Senparc:DefaultCO2NETCache111:Container:Senparc.Weixin.MP.Containers.AccessTokenBag:wx11676b7958ea1f6e`

这些分级是为了避免在全局中的键冲突，是很有必要的。你不需要记住这些key，另外这个长度也不会影响程序效率。
