### ISSUE TITLE
The SSL connection could not be established, see inner exception

### ISSUE THREAD

**Issue by KINGGUOKUN** [Senparc/Senparc.CO2NET#185]
core 3.1 HttpClient默认是启用服务端证书校验的，而CO2NET默认没有关闭或者默认直接通过服务端证书校验，导致请求微信相关API时候出错：The SSL connection could not be established, see inner exception。目前我的临时解决方案如下：
services.AddHttpClient("elite-wechat")
.ConfigurePrimaryHttpMessageHandler(() =>
{
var httpClientHandler = HttpClientHelper.GetHttpClientHandler(null, RequestUtility.SenparcHttpClientWebProxy, System.Net.DecompressionMethods.GZip);
//httpClientHandler.ClientCertificates.Add(cert);
httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errir) => true;

                         return httpClientHandler;
                     });

**Comment by JeffreySu** [comment]
@KINGGUOKUN  你是在 Linux 下面吗？比如CentOS？

**Comment by JeffreySu** [comment]
如果是的话可以参考一下这里的配置：https://github.com/JeffreySu/WeiXinMPSDK/issues/2207#issuecomment-701191258

**Comment by KINGGUOKUN** [comment]
嗯，的确是在CentOS下面。通过环境变量确实可以起效，但socket通信会回退到2.0的Handler。我还是通过手动设置HTTPClientHandler的服务端证书校验回调给绕过了。

**Comment by JeffreySu** [comment]
感谢提供信息！
