### ISSUE TITLE
RequestUtility.HttpGet的serviceProvider 参数为必填，.NetFramework4.5 环境下无法调用

### ISSUE THREAD

**Issue by wechatdeveloper** [Senparc/Senparc.CO2NET#194]
以下方法，serviceProvider 是必填参数，在.NetFramework 4.5 环境中，无法调用  ？

` /// <summary>
        /// 使用Get方法获取字符串结果（没有加入Cookie）
        /// </summary>
        /// <param name="serviceProvider">.NetCore 下的服务器提供程序，如果 .NET Framework 则保留 null</param>
        /// <param name="url"></param>
        /// <param name="encoding"></param>
        /// <returns></returns>
        public static string HttpGet(
            IServiceProvider serviceProvider,
            string url, Encoding encoding = null)`

**Comment by JeffreySu** [comment]
传入 null 即可。

**Comment by JeffreySu** [comment]
这个参数应该有注释：`.NetCore 下的服务器提供程序，如果 .NET Framework 则保留 null`
