### ISSUE TITLE
项目打开报错。我是为了用weixin.mp编译不过去才过来找这个项目的

### ISSUE THREAD

**Issue by gselec** [Senparc/Senparc.CO2NET#21]
项目打开报错。我是为了用weixin.mp编译不过去才过来找这个项目的。
vs2015打开项目报错：xml需要是ms build。

咱能别这么啰嗦吗？感觉为了写程序而写程序了，一层层一圈圈的绕。

**Comment by JeffreySu** [comment]
关于编译的问题：
1、Senparc.Weixin.MP 编译不过去通常不会是因为这里的原因，不需要调试这个包。这个包的定位类似于Newtonsoft.Json一样的组件，已经粒度很小，你只需要输入和输出，里面发生的事情通常不用管，如果需要调试，建议用单元测试来模拟。
2、这个项目因为用到了multi-targeting，所以只有VS2017以上的才能支持。
3、可以直接说一下你碰到的问题，以便可以帮到你。

谢谢反馈！
