### ISSUE TITLE
Post.PostGetJson方法的Dictionary<string, string> formData无法应对复杂类型

### ISSUE THREAD

**Issue by chenjingchun** [Senparc/Senparc.CO2NET#38]
{"a":"abc","b":[{"aa":"v","bb":"v"},{"aa":"v","bb":"v"}]}像包含了集合的，怎样传递？

**Comment by JeffreySu** [comment]
@chenjingchun  转成Json字符串，Post和Get参数就是字符串

**Comment by chenjingchun** [comment]
像这个{"a":"abc","b":[{"aa":"v","bb":"v"},{"aa":"v","bb":"v"}]}，我要再封装一层
`{“obj”:      "{a:abc,b:[{aa:v,bb:v},{aa:v,bb:v}]}"        }`
或者b的集合对象转成string类型Json
`{"a":"abc","b":     "[{aa:v,bb:v},{aa:v,bb:v}]"    }`
我自己写的webapi，这样的话要多一次转换。

**Comment by JeffreySu** [comment]
最终序列化变成字符串这一步是无论如何都少不了的，只不过是你做还是插件做的区别。
