### ISSUE TITLE
关于微信请求消息MessageHandler和OnExecuted消息顺序问题

### ISSUE THREAD

**Issue by linjia11lu** [Senparc/Senparc.CO2NET#39]
问题说明：我在OnEvent_ScanRequest事件里面返回了一个多文本消息（7张图片,标题,链接），然后在OnExecuted方法里发送一条模板消息，结果总是先收到模板消息后才收到多文本消息。
经过代码调试发现，代码是先执行OnEvent_ScanRequest事件后再执行OnExecuted方法的，我希望是先收到多文本消息后再收到模板消息的。。。

**Comment by linjia11lu** [comment]
经过测试 在OnEvent_ScanRequest事件里发送一条模板消息...在OnExecuted方法里发送一条模板消息...顺序是正常的...

**Comment by JeffreySu** [comment]
你的模板消息是立即发送的，你设置的常规ResponseMessage是会在整个请求完成之后才发送的，这个是微信的消息通讯机制决定的，如果你要顺序换一下不防用我们的队列，延迟个1秒钟。

**Comment by linjia11lu** [comment]
感谢...作者的建议很顺利解决了我的问题...
