### ISSUE TITLE
RequestUtility.HttpPost突然获取不到参数

### ISSUE THREAD

**Issue by lb0726** [Senparc/Senparc.CO2NET#48]
Dictionary<string, string> formData = new Dictionary<string, string>();
formData.Add("test", DateTime.Now.Ticks.ToString());
formData.Add("formdata", formDataJson);

string strJson = RequestUtility.HttpPost(url, null, formData, UTF8Encoding.UTF8);

传入test 和 formdata，但是在url这个页面去request.form["test"]取不到test参数
2.16版本

**Comment by JeffreySu** [comment]
你如果直接用action里面的参数 public ActionResult Address(string test) 能娶到吗？

**Comment by lb0726** [comment]
只要不用这个RequestUtility.HttpPost就是正常的

**Comment by lb0726** [comment]
#region 只需要使用同步的方法

        /// <summary>
        /// 组装QueryString的方法
        /// 参数之间用&amp;连接，首位没有符号，如：a=1&amp;b=2&amp;c=3
        /// </summary>
        /// <param name="formData"></param>
        /// <returns></returns>
        public static string GetQueryString(this Dictionary<string, string> formData)
        {
            if (formData == null || formData.Count == 0)
            {
                return "";
            }

            StringBuilder sb = new StringBuilder();

            var i = 0;
            foreach (var kv in formData)
            {
                i++;
                sb.AppendFormat("{0}={1}", kv.Key, kv.Value);
                if (i < formData.Count)
                {
                    sb.Append("&");
                }
            }

            return sb.ToString();
        }
扩展的这个方法,如果kv.Value中有特殊的&号会出现问题吧。难道字典传入进来的kv.Value就去先编码？

**Comment by JeffreySu** [comment]
@lb0726  这是一个设计上的缺陷，确实应该编码一下。
