### ISSUE TITLE
建议用DateTimeOffset替换DateTime

### ISSUE THREAD

**Issue by hanabi1224** [Senparc/Senparc.CO2NET#59]
DateTimeOffset包含时区信息  DateTimeOffset.UtcNow和DateTimeOffset.Now是一样的，使用DateTime类型传递，序列化反序列化很容易搞错时区出bug

**Comment by JeffreySu** [comment]
确实是这样的。这个库里面已经提供了一个SystemTime的类，用于扩展DateTime，我们会将其改进为DateTimeOffset，感谢建议！

**Comment by JeffreySu** [comment]
@hanabi1224  你上面是不是想说“DateTime.UtcNow和DateTimeOffset.Now是一样的”？

**Comment by JeffreySu** [comment]
最新的preview已经改为DateTimeOffset。
另外，目前使用的序列化都是带市区信息的，也就是dateTime.ToString()和dateTimeOffset.ToString()结果是一样的，仍然可以放心使用。

**Comment by hanabi1224** [comment]
@JeffreySu 谢谢～  赞效率！

**Comment by JeffreySu** [comment]
已经发布到到最新的正式版中 https://www.nuget.org/packages/Senparc.CO2NET/0.4.4，感谢！
