### ISSUE TITLE
解析加密字符串的时候报错Padding is invalid and cannot be removed

### ISSUE THREAD

**Issue by Rstar-Yan** [Senparc/Senparc.CO2NET#90]
偶尔解析手机号加密数据的时候会有这个问题调用的方法是Senparc.Weixin.WxOpen.Helpers.EncryptHelper.DecodeEncryptedData()
请问是什么原因

**Comment by JeffreySu** [comment]
如果给的加密字符串、向量（iv）都正确的话不应该会有问题，你能收集到这些错误发生时候的具体参数吗？
