### ISSUE TITLE
Framework跟.net core兼容性问题

### ISSUE THREAD

**Issue by laozhuorun** [Senparc/Senparc.CO2NET#96]
AddSenparcGlobalServices 不支持Framework，BuildFromWebConfig 又不支持.net core，，如果同时使用了两个（我的项目因为一些原因不得不同时依赖framework跟.netcore），注册逻辑就要写两套，太麻烦了！还不如旧的sdk兼容性好！

**Comment by laozhuorun** [comment]
明明可以用过一个接口注册配置，非要滥用各种config文件，为了用而用

**Comment by JeffreySu** [comment]
您好，可能您对 .NET Framework（以下简称.NET） 和 .NET Core 的配置差异还不太了解，我大概说一下两者和您所说的方法的差别之处：

1、.NET 的默认配置文件是 web.config，字符串配置存放在 `<appSettings>` 节点下面，这时候如果要将一系列setting配置到一个实例中，需要自己写方法，这个就是 BuildFromWebConfig 的由来；而 .NET Core 默认配置在 appsettings.json 文件中（虽然也支持 web.config，不过官方并不推荐这么做），这个读取过程是半自动的（需要自己写 DI 注入），因此并不需要 BuildFromWebConfig 。

所以关于您说的“明明可以用过一个接口注册配置”的说法从框架本身来说理解是不正确的，两个框架本身就提供了2种不同的配置文件，尤其作为一个开放项目，区分对待是合理的。

2、由于 .NET Core 自己的一整套 DI（依赖注入） 体系，所以扩展的模块大都需要使用 service.AddXXX() 的方式进行注册以及做 BuildServiceProvider 之前的准备工作（这几乎是必须的），这套默认的 DI 的体系是 .NET Framework 中没有的，因此 AddSenparcGlobalServices() 方法也只在 .NET Core 中提供，而在 .NET 中是不需要（也没有办法使用）的，AddSenparcGlobalServices() `和 Web.config 没有任何关系，和BuildFromWebConfig() 也没有关系，只是2个框架本身的差异罢了 `。


另外补充一点，如果碰到`同时依赖framework跟.netcore`这样的情况，`一般`是在 .net standard 标准范畴下的，建议按照 .net standard 的方式来做，可以做到更好的兼容性。
